name: f_twitter_social_media_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/  # Points to the folder containing the font file

  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/twitter_icon.ttf  # Updated font file name
